[workspace]
resolver = "2"
members = ["bevy_spacetimedb", "macros", "example_app"]

[workspace.dependencies]

bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
spacetimedb-sdk = { version = "1.3.0" }
