// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GalaxySettings {
    pub seed: u64,
    pub dimensions: f64,
    pub systems_distance: f64,
    pub sectors_size: f64,
}

impl __sdk::InModule for GalaxySettings {
    type Module = super::RemoteModule;
}
