// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::game_server_type::GameServer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_servers`.
///
/// Obtain a handle from the [`GameServersTableAccess::game_servers`] method on [`super::RemoteTables`],
/// like `ctx.db.game_servers()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_servers().on_insert(...)`.
pub struct GameServersTableHandle<'ctx> {
    imp: __sdk::TableHandle<GameServer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_servers`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameServersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameServersTableHandle`], which mediates access to the table `game_servers`.
    fn game_servers(&self) -> GameServersTableHandle<'_>;
}

impl GameServersTableAccess for super::RemoteTables {
    fn game_servers(&self) -> GameServersTableHandle<'_> {
        GameServersTableHandle {
            imp: self.imp.get_table::<GameServer>("game_servers"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameServersInsertCallbackId(__sdk::CallbackId);
pub struct GameServersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GameServersTableHandle<'ctx> {
    type Row = GameServer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GameServer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameServersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameServersInsertCallbackId {
        GameServersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameServersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameServersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameServersDeleteCallbackId {
        GameServersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameServersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GameServer>("game_servers");
    _table.add_unique_constraint::<__sdk::Identity>("id", |row| &row.id);
    _table.add_unique_constraint::<u32>("current_system", |row| &row.current_system);
}
pub struct GameServersUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameServersTableHandle<'ctx> {
    type UpdateCallbackId = GameServersUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameServersUpdateCallbackId {
        GameServersUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameServersUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<GameServer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GameServer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `game_servers`,
/// which allows point queries on the field of the same name
/// via the [`GameServersIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_servers().id().find(...)`.
pub struct GameServersIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GameServer, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameServersTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `game_servers`.
    pub fn id(&self) -> GameServersIdUnique<'ctx> {
        GameServersIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameServersIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<GameServer> {
        self.imp.find(col_val)
    }
}

/// Access to the `current_system` unique index on the table `game_servers`,
/// which allows point queries on the field of the same name
/// via the [`GameServersCurrentSystemUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_servers().current_system().find(...)`.
pub struct GameServersCurrentSystemUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GameServer, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameServersTableHandle<'ctx> {
    /// Get a handle on the `current_system` unique index on the table `game_servers`.
    pub fn current_system(&self) -> GameServersCurrentSystemUnique<'ctx> {
        GameServersCurrentSystemUnique {
            imp: self.imp.get_unique_constraint::<u32>("current_system"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameServersCurrentSystemUnique<'ctx> {
    /// Find the subscribed row whose `current_system` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<GameServer> {
        self.imp.find(col_val)
    }
}
