// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GeneratePointsArgs {}

impl From<GeneratePointsArgs> for super::Reducer {
    fn from(args: GeneratePointsArgs) -> Self {
        Self::GeneratePoints
    }
}

impl __sdk::InModule for GeneratePointsArgs {
    type Module = super::RemoteModule;
}

pub struct GeneratePointsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `generate_points`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait generate_points {
    /// Request that the remote module invoke the reducer `generate_points` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_generate_points`] callbacks.
    fn generate_points(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `generate_points`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`GeneratePointsCallbackId`] can be passed to [`Self::remove_on_generate_points`]
    /// to cancel the callback.
    fn on_generate_points(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> GeneratePointsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_generate_points`],
    /// causing it not to run in the future.
    fn remove_on_generate_points(&self, callback: GeneratePointsCallbackId);
}

impl generate_points for super::RemoteReducers {
    fn generate_points(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("generate_points", GeneratePointsArgs {})
    }
    fn on_generate_points(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> GeneratePointsCallbackId {
        GeneratePointsCallbackId(self.imp.on_reducer(
            "generate_points",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::GeneratePoints {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_generate_points(&self, callback: GeneratePointsCallbackId) {
        self.imp.remove_on_reducer("generate_points", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `generate_points`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_generate_points {
    /// Set the call-reducer flags for the reducer `generate_points` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn generate_points(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_generate_points for super::SetReducerFlags {
    fn generate_points(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("generate_points", flags);
    }
}
