// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GsPlayerConnectedArgs {
    pub player_id: u64,
}

impl From<GsPlayerConnectedArgs> for super::Reducer {
    fn from(args: GsPlayerConnectedArgs) -> Self {
        Self::GsPlayerConnected {
            player_id: args.player_id,
        }
    }
}

impl __sdk::InModule for GsPlayerConnectedArgs {
    type Module = super::RemoteModule;
}

pub struct GsPlayerConnectedCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `gs_player_connected`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait gs_player_connected {
    /// Request that the remote module invoke the reducer `gs_player_connected` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_gs_player_connected`] callbacks.
    fn gs_player_connected(&self, player_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `gs_player_connected`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`GsPlayerConnectedCallbackId`] can be passed to [`Self::remove_on_gs_player_connected`]
    /// to cancel the callback.
    fn on_gs_player_connected(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> GsPlayerConnectedCallbackId;
    /// Cancel a callback previously registered by [`Self::on_gs_player_connected`],
    /// causing it not to run in the future.
    fn remove_on_gs_player_connected(&self, callback: GsPlayerConnectedCallbackId);
}

impl gs_player_connected for super::RemoteReducers {
    fn gs_player_connected(&self, player_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("gs_player_connected", GsPlayerConnectedArgs { player_id })
    }
    fn on_gs_player_connected(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> GsPlayerConnectedCallbackId {
        GsPlayerConnectedCallbackId(self.imp.on_reducer(
            "gs_player_connected",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::GsPlayerConnected { player_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, player_id)
            }),
        ))
    }
    fn remove_on_gs_player_connected(&self, callback: GsPlayerConnectedCallbackId) {
        self.imp
            .remove_on_reducer("gs_player_connected", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `gs_player_connected`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_gs_player_connected {
    /// Set the call-reducer flags for the reducer `gs_player_connected` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn gs_player_connected(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_gs_player_connected for super::SetReducerFlags {
    fn gs_player_connected(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("gs_player_connected", flags);
    }
}
