// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GsPlayerDisconnectedArgs {
    pub player_identity: __sdk::Identity,
}

impl From<GsPlayerDisconnectedArgs> for super::Reducer {
    fn from(args: GsPlayerDisconnectedArgs) -> Self {
        Self::GsPlayerDisconnected {
            player_identity: args.player_identity,
        }
    }
}

impl __sdk::InModule for GsPlayerDisconnectedArgs {
    type Module = super::RemoteModule;
}

pub struct GsPlayerDisconnectedCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `gs_player_disconnected`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait gs_player_disconnected {
    /// Request that the remote module invoke the reducer `gs_player_disconnected` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_gs_player_disconnected`] callbacks.
    fn gs_player_disconnected(&self, player_identity: __sdk::Identity) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `gs_player_disconnected`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`GsPlayerDisconnectedCallbackId`] can be passed to [`Self::remove_on_gs_player_disconnected`]
    /// to cancel the callback.
    fn on_gs_player_disconnected(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity) + Send + 'static,
    ) -> GsPlayerDisconnectedCallbackId;
    /// Cancel a callback previously registered by [`Self::on_gs_player_disconnected`],
    /// causing it not to run in the future.
    fn remove_on_gs_player_disconnected(&self, callback: GsPlayerDisconnectedCallbackId);
}

impl gs_player_disconnected for super::RemoteReducers {
    fn gs_player_disconnected(&self, player_identity: __sdk::Identity) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "gs_player_disconnected",
            GsPlayerDisconnectedArgs { player_identity },
        )
    }
    fn on_gs_player_disconnected(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity) + Send + 'static,
    ) -> GsPlayerDisconnectedCallbackId {
        GsPlayerDisconnectedCallbackId(self.imp.on_reducer(
            "gs_player_disconnected",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::GsPlayerDisconnected { player_identity },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, player_identity)
            }),
        ))
    }
    fn remove_on_gs_player_disconnected(&self, callback: GsPlayerDisconnectedCallbackId) {
        self.imp
            .remove_on_reducer("gs_player_disconnected", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `gs_player_disconnected`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_gs_player_disconnected {
    /// Set the call-reducer flags for the reducer `gs_player_disconnected` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn gs_player_disconnected(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_gs_player_disconnected for super::SetReducerFlags {
    fn gs_player_disconnected(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("gs_player_disconnected", flags);
    }
}
