// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GsRegisterArgs {
    pub ip: String,
    pub port: u16,
}

impl From<GsRegisterArgs> for super::Reducer {
    fn from(args: GsRegisterArgs) -> Self {
        Self::GsRegister {
            ip: args.ip,
            port: args.port,
        }
    }
}

impl __sdk::InModule for GsRegisterArgs {
    type Module = super::RemoteModule;
}

pub struct GsRegisterCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `gs_register`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait gs_register {
    /// Request that the remote module invoke the reducer `gs_register` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_gs_register`] callbacks.
    fn gs_register(&self, ip: String, port: u16) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `gs_register`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`GsRegisterCallbackId`] can be passed to [`Self::remove_on_gs_register`]
    /// to cancel the callback.
    fn on_gs_register(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &u16) + Send + 'static,
    ) -> GsRegisterCallbackId;
    /// Cancel a callback previously registered by [`Self::on_gs_register`],
    /// causing it not to run in the future.
    fn remove_on_gs_register(&self, callback: GsRegisterCallbackId);
}

impl gs_register for super::RemoteReducers {
    fn gs_register(&self, ip: String, port: u16) -> __sdk::Result<()> {
        self.imp
            .call_reducer("gs_register", GsRegisterArgs { ip, port })
    }
    fn on_gs_register(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &u16) + Send + 'static,
    ) -> GsRegisterCallbackId {
        GsRegisterCallbackId(self.imp.on_reducer(
            "gs_register",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::GsRegister { ip, port },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, ip, port)
            }),
        ))
    }
    fn remove_on_gs_register(&self, callback: GsRegisterCallbackId) {
        self.imp.remove_on_reducer("gs_register", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `gs_register`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_gs_register {
    /// Set the call-reducer flags for the reducer `gs_register` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn gs_register(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_gs_register for super::SetReducerFlags {
    fn gs_register(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("gs_register", flags);
    }
}
