// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GsSetReadyArgs {}

impl From<GsSetReadyArgs> for super::Reducer {
    fn from(args: GsSetReadyArgs) -> Self {
        Self::GsSetReady
    }
}

impl __sdk::InModule for GsSetReadyArgs {
    type Module = super::RemoteModule;
}

pub struct GsSetReadyCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `gs_set_ready`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait gs_set_ready {
    /// Request that the remote module invoke the reducer `gs_set_ready` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_gs_set_ready`] callbacks.
    fn gs_set_ready(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `gs_set_ready`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`GsSetReadyCallbackId`] can be passed to [`Self::remove_on_gs_set_ready`]
    /// to cancel the callback.
    fn on_gs_set_ready(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> GsSetReadyCallbackId;
    /// Cancel a callback previously registered by [`Self::on_gs_set_ready`],
    /// causing it not to run in the future.
    fn remove_on_gs_set_ready(&self, callback: GsSetReadyCallbackId);
}

impl gs_set_ready for super::RemoteReducers {
    fn gs_set_ready(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("gs_set_ready", GsSetReadyArgs {})
    }
    fn on_gs_set_ready(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> GsSetReadyCallbackId {
        GsSetReadyCallbackId(self.imp.on_reducer(
            "gs_set_ready",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::GsSetReady {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_gs_set_ready(&self, callback: GsSetReadyCallbackId) {
        self.imp.remove_on_reducer("gs_set_ready", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `gs_set_ready`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_gs_set_ready {
    /// Set the call-reducer flags for the reducer `gs_set_ready` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn gs_set_ready(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_gs_set_ready for super::SetReducerFlags {
    fn gs_set_ready(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("gs_set_ready", flags);
    }
}
