// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct OnDisconnectedArgs {}

impl From<OnDisconnectedArgs> for super::Reducer {
    fn from(args: OnDisconnectedArgs) -> Self {
        Self::OnDisconnected
    }
}

impl __sdk::InModule for OnDisconnectedArgs {
    type Module = super::RemoteModule;
}

pub struct OnDisconnectedCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `on_disconnected`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait on_disconnected {
    /// Request that the remote module invoke the reducer `on_disconnected` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_on_disconnected`] callbacks.
    fn on_disconnected(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `on_disconnected`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`OnDisconnectedCallbackId`] can be passed to [`Self::remove_on_on_disconnected`]
    /// to cancel the callback.
    fn on_on_disconnected(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> OnDisconnectedCallbackId;
    /// Cancel a callback previously registered by [`Self::on_on_disconnected`],
    /// causing it not to run in the future.
    fn remove_on_on_disconnected(&self, callback: OnDisconnectedCallbackId);
}

impl on_disconnected for super::RemoteReducers {
    fn on_disconnected(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("on_disconnected", OnDisconnectedArgs {})
    }
    fn on_on_disconnected(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> OnDisconnectedCallbackId {
        OnDisconnectedCallbackId(self.imp.on_reducer(
            "on_disconnected",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::OnDisconnected {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_on_disconnected(&self, callback: OnDisconnectedCallbackId) {
        self.imp.remove_on_reducer("on_disconnected", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `on_disconnected`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_on_disconnected {
    /// Set the call-reducer flags for the reducer `on_disconnected` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn on_disconnected(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_on_disconnected for super::SetReducerFlags {
    fn on_disconnected(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("on_disconnected", flags);
    }
}
