// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::planet_type::Planet;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `planets`.
///
/// Obtain a handle from the [`PlanetsTableAccess::planets`] method on [`super::RemoteTables`],
/// like `ctx.db.planets()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.planets().on_insert(...)`.
pub struct PlanetsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Planet>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `planets`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlanetsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlanetsTableHandle`], which mediates access to the table `planets`.
    fn planets(&self) -> PlanetsTableHandle<'_>;
}

impl PlanetsTableAccess for super::RemoteTables {
    fn planets(&self) -> PlanetsTableHandle<'_> {
        PlanetsTableHandle {
            imp: self.imp.get_table::<Planet>("planets"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlanetsInsertCallbackId(__sdk::CallbackId);
pub struct PlanetsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlanetsTableHandle<'ctx> {
    type Row = Planet;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Planet> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlanetsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlanetsInsertCallbackId {
        PlanetsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlanetsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlanetsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlanetsDeleteCallbackId {
        PlanetsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlanetsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Planet>("planets");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct PlanetsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlanetsTableHandle<'ctx> {
    type UpdateCallbackId = PlanetsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlanetsUpdateCallbackId {
        PlanetsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlanetsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Planet>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Planet>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `planets`,
/// which allows point queries on the field of the same name
/// via the [`PlanetsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.planets().id().find(...)`.
pub struct PlanetsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Planet, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlanetsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `planets`.
    pub fn id(&self) -> PlanetsIdUnique<'ctx> {
        PlanetsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlanetsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Planet> {
        self.imp.find(col_val)
    }
}
