// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Planet {
    pub id: u64,
    pub system_id: u32,
    pub planet_index: u8,
    pub name: String,
    pub distance: f32,
    pub radius: f32,
    pub mass: f32,
}

impl __sdk::InModule for Planet {
    type Module = super::RemoteModule;
}
