// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_type::Player;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `players`.
///
/// Obtain a handle from the [`PlayersTableAccess::players`] method on [`super::RemoteTables`],
/// like `ctx.db.players()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.players().on_insert(...)`.
pub struct PlayersTableHandle<'ctx> {
    imp: __sdk::TableHandle<Player>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `players`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayersTableHandle`], which mediates access to the table `players`.
    fn players(&self) -> PlayersTableHandle<'_>;
}

impl PlayersTableAccess for super::RemoteTables {
    fn players(&self) -> PlayersTableHandle<'_> {
        PlayersTableHandle {
            imp: self.imp.get_table::<Player>("players"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayersInsertCallbackId(__sdk::CallbackId);
pub struct PlayersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayersTableHandle<'ctx> {
    type Row = Player;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Player> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayersInsertCallbackId {
        PlayersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayersDeleteCallbackId {
        PlayersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Player>("players");
    _table.add_unique_constraint::<__sdk::Identity>("id", |row| &row.id);
    _table.add_unique_constraint::<u64>("external_id", |row| &row.external_id);
}
pub struct PlayersUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayersTableHandle<'ctx> {
    type UpdateCallbackId = PlayersUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayersUpdateCallbackId {
        PlayersUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayersUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Player>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Player>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `players`,
/// which allows point queries on the field of the same name
/// via the [`PlayersIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.players().id().find(...)`.
pub struct PlayersIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Player, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayersTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `players`.
    pub fn id(&self) -> PlayersIdUnique<'ctx> {
        PlayersIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayersIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Player> {
        self.imp.find(col_val)
    }
}

/// Access to the `external_id` unique index on the table `players`,
/// which allows point queries on the field of the same name
/// via the [`PlayersExternalIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.players().external_id().find(...)`.
pub struct PlayersExternalIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Player, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayersTableHandle<'ctx> {
    /// Get a handle on the `external_id` unique index on the table `players`.
    pub fn external_id(&self) -> PlayersExternalIdUnique<'ctx> {
        PlayersExternalIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("external_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayersExternalIdUnique<'ctx> {
    /// Find the subscribed row whose `external_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Player> {
        self.imp.find(col_val)
    }
}
