// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerRegisterArgs {
    pub external_id: u64,
}

impl From<PlayerRegisterArgs> for super::Reducer {
    fn from(args: PlayerRegisterArgs) -> Self {
        Self::PlayerRegister {
            external_id: args.external_id,
        }
    }
}

impl __sdk::InModule for PlayerRegisterArgs {
    type Module = super::RemoteModule;
}

pub struct PlayerRegisterCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_register`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_register {
    /// Request that the remote module invoke the reducer `player_register` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_player_register`] callbacks.
    fn player_register(&self, external_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `player_register`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PlayerRegisterCallbackId`] can be passed to [`Self::remove_on_player_register`]
    /// to cancel the callback.
    fn on_player_register(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> PlayerRegisterCallbackId;
    /// Cancel a callback previously registered by [`Self::on_player_register`],
    /// causing it not to run in the future.
    fn remove_on_player_register(&self, callback: PlayerRegisterCallbackId);
}

impl player_register for super::RemoteReducers {
    fn player_register(&self, external_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("player_register", PlayerRegisterArgs { external_id })
    }
    fn on_player_register(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> PlayerRegisterCallbackId {
        PlayerRegisterCallbackId(self.imp.on_reducer(
            "player_register",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PlayerRegister { external_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, external_id)
            }),
        ))
    }
    fn remove_on_player_register(&self, callback: PlayerRegisterCallbackId) {
        self.imp.remove_on_reducer("player_register", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `player_register`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_player_register {
    /// Set the call-reducer flags for the reducer `player_register` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn player_register(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_player_register for super::SetReducerFlags {
    fn player_register(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("player_register", flags);
    }
}
