// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::body_types_type::BodyTypes;
use super::star_system_type::StarSystem;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `star_systems`.
///
/// Obtain a handle from the [`StarSystemsTableAccess::star_systems`] method on [`super::RemoteTables`],
/// like `ctx.db.star_systems()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.star_systems().on_insert(...)`.
pub struct StarSystemsTableHandle<'ctx> {
    imp: __sdk::TableHandle<StarSystem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `star_systems`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StarSystemsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StarSystemsTableHandle`], which mediates access to the table `star_systems`.
    fn star_systems(&self) -> StarSystemsTableHandle<'_>;
}

impl StarSystemsTableAccess for super::RemoteTables {
    fn star_systems(&self) -> StarSystemsTableHandle<'_> {
        StarSystemsTableHandle {
            imp: self.imp.get_table::<StarSystem>("star_systems"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StarSystemsInsertCallbackId(__sdk::CallbackId);
pub struct StarSystemsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StarSystemsTableHandle<'ctx> {
    type Row = StarSystem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StarSystem> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StarSystemsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StarSystemsInsertCallbackId {
        StarSystemsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StarSystemsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StarSystemsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StarSystemsDeleteCallbackId {
        StarSystemsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StarSystemsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StarSystem>("star_systems");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}
pub struct StarSystemsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StarSystemsTableHandle<'ctx> {
    type UpdateCallbackId = StarSystemsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StarSystemsUpdateCallbackId {
        StarSystemsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StarSystemsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<StarSystem>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StarSystem>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `star_systems`,
/// which allows point queries on the field of the same name
/// via the [`StarSystemsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.star_systems().id().find(...)`.
pub struct StarSystemsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StarSystem, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StarSystemsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `star_systems`.
    pub fn id(&self) -> StarSystemsIdUnique<'ctx> {
        StarSystemsIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StarSystemsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<StarSystem> {
        self.imp.find(col_val)
    }
}

/// Access to the `name` unique index on the table `star_systems`,
/// which allows point queries on the field of the same name
/// via the [`StarSystemsNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.star_systems().name().find(...)`.
pub struct StarSystemsNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StarSystem, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StarSystemsTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `star_systems`.
    pub fn name(&self) -> StarSystemsNameUnique<'ctx> {
        StarSystemsNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StarSystemsNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<StarSystem> {
        self.imp.find(col_val)
    }
}
