// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::subject_type::Subject;
use super::subject_type_type::SubjectType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `subjects`.
///
/// Obtain a handle from the [`SubjectsTableAccess::subjects`] method on [`super::RemoteTables`],
/// like `ctx.db.subjects()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subjects().on_insert(...)`.
pub struct SubjectsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Subject>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `subjects`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SubjectsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SubjectsTableHandle`], which mediates access to the table `subjects`.
    fn subjects(&self) -> SubjectsTableHandle<'_>;
}

impl SubjectsTableAccess for super::RemoteTables {
    fn subjects(&self) -> SubjectsTableHandle<'_> {
        SubjectsTableHandle {
            imp: self.imp.get_table::<Subject>("subjects"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SubjectsInsertCallbackId(__sdk::CallbackId);
pub struct SubjectsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SubjectsTableHandle<'ctx> {
    type Row = Subject;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Subject> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SubjectsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SubjectsInsertCallbackId {
        SubjectsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SubjectsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SubjectsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SubjectsDeleteCallbackId {
        SubjectsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SubjectsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Subject>("subjects");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}
pub struct SubjectsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SubjectsTableHandle<'ctx> {
    type UpdateCallbackId = SubjectsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SubjectsUpdateCallbackId {
        SubjectsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SubjectsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Subject>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Subject>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `identity` unique index on the table `subjects`,
/// which allows point queries on the field of the same name
/// via the [`SubjectsIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subjects().identity().find(...)`.
pub struct SubjectsIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Subject, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SubjectsTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `subjects`.
    pub fn identity(&self) -> SubjectsIdentityUnique<'ctx> {
        SubjectsIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SubjectsIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Subject> {
        self.imp.find(col_val)
    }
}
